export const ROUTES = {
  // Auth
  AUTH_STACK: 'AuthStack',
  SIGN_IN: 'SignIn',
  SIGN_UP: 'SignUp',
  OTP: 'Otp',
  // Main
  MAIN_STACK: 'MainStack',
  HOME: 'Home',
  CALENDAR: 'Calendar',
  SEARCH: 'Search',
  PROFILE: 'Profile',
  PROFILE_STACK: 'ProfileStack',
  PROFILE_INFO: 'ProfileInfo',
  // Others
  DETAILS: 'Details',
  // Modals
  MODAL: 'Modal',
  // Tabs
  TAB_STACK: 'TabStack',
  // Notifications
  NOTIFY: 'Notify',
  // Settings
  SETTINGS: 'Settings',
  // Others
  ABOUT: 'About',
  HELP: 'Help',
  TERMS: 'Terms',
  PRIVACY: 'Privacy',
  // Auth
  FORGOT_PASSWORD: 'ForgotPassword',
  RESET_PASSWORD: 'ResetPassword',
};
